load NJGAS.dat;
resample_size=length(NJGAS);
sample_mean=sum(NJGAS)/resample_size;
resample_time=1000;
index=randi([1 resample_size],resample_time,resample_size);
resampled_data=NJGAS(index);
erd=sum(resampled_data,2)/resample_size-sample_mean;
erd_sorted=sort(erd);
delta=erd_sorted(fix([0.025 0.975]*resample_time));
int=sample_mean-[delta(2) delta(1)];
disp(strcat('The 95% interval is [',num2str(int(1)),', ',num2str(int(2)),']'));